- alias: Trigger when downstairs boiler changes state
  trigger:
    platform: state
    entity_id: climate.downstairs
  action:
    - service: mqtt.publish
      data_template:
        topic: "brompton/downstairs/climate/{{ trigger.to_state.attributes.hvac_action }}" # brompton/downstairs/climate/heating
        payload: "test message"
#    service: script.notify_mqtt_climate
#    data_template:
#      zone: downstairs
#      mode: "{{ trigger.to_state.attributes.hvac_action }}" # heating, idle