- id: '1613741702888'
  alias: Turn off lights after sunrise and open blinds
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: +00:20:00
  condition: []
  action:
  - type: turn_off
    device_id: 64cad46a7610b5987b7ffd884ba0e07a
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_off
    device_id: 54a1fd0f3d5484107745440e81c74171
    entity_id: light.ikea_kitchen_lamp
    domain: light
  - device_id: 1e386b5613942db415a2d70d3d37a09b
    domain: cover
    entity_id: cover.ikea_kitchen_blind_left
    type: set_position
    position: 100
  - device_id: fd2868cfafdfa78ecf3c1cb25f925c53
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_left
    type: set_position
    position: 100
  - device_id: b964938e4137cac9e362d8e58c46735c
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_right
    type: set_position
    position: 100
  - device_id: 954f073b4ae1047e8c0eee6fafa2c966
    domain: cover
    entity_id: cover.ikea_kitchen_blind_right
    type: set_position
    position: 100
  mode: single
- id: '1613741842726'
  alias: Turn off lights at bedtime
  description: ''
  trigger:
  - platform: time
    at: '22:30'
  condition: []
  action:
  - type: turn_off
    device_id: 64cad46a7610b5987b7ffd884ba0e07a
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_off
    device_id: 54a1fd0f3d5484107745440e81c74171
    entity_id: light.ikea_kitchen_lamp
    domain: light
  mode: single
- id: '1613741995095'
  alias: Turn on lights and lower blinds at dusk
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:20:00
  condition: []
  action:
  - type: turn_on
    device_id: 64cad46a7610b5987b7ffd884ba0e07a
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_on
    device_id: 54a1fd0f3d5484107745440e81c74171
    entity_id: light.ikea_kitchen_lamp
    domain: light
    enabled: true
  - device_id: 1e386b5613942db415a2d70d3d37a09b
    domain: cover
    entity_id: cover.ikea_kitchen_blind_left
    type: set_position
    position: 50
    enabled: true
  - device_id: fd2868cfafdfa78ecf3c1cb25f925c53
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_left
    type: set_position
    position: 50
    enabled: true
  - device_id: b964938e4137cac9e362d8e58c46735c
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_right
    type: set_position
    position: 50
    enabled: true
  - device_id: 954f073b4ae1047e8c0eee6fafa2c966
    domain: cover
    entity_id: cover.ikea_kitchen_blind_right
    type: set_position
    position: 50
    enabled: true
  mode: single
- id: '1613742091259'
  alias: Turn on lights in the morning
  description: ''
  trigger:
  - platform: time
    at: 06:35
  - platform: time
    at: 07:30
  condition:
  - condition: sun
    before: sunrise
  - condition: or
    conditions:
    - condition: time
      after: 06:34
      weekday:
      - mon
      - tue
      - wed
    - condition: time
      after: 07:29
      weekday:
      - thu
      - fri
      - sat
      - sun
  action:
  - type: turn_on
    device_id: 64cad46a7610b5987b7ffd884ba0e07a
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_on
    device_id: 54a1fd0f3d5484107745440e81c74171
    entity_id: light.ikea_kitchen_lamp
    domain: light
    enabled: false
  mode: single
- id: '1614714623032'
  alias: Close blinds fully after sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:20:00
  condition: []
  action:
  - device_id: 1e386b5613942db415a2d70d3d37a09b
    domain: cover
    entity_id: cover.ikea_kitchen_blind_left
    type: set_position
    position: 0
  - device_id: fd2868cfafdfa78ecf3c1cb25f925c53
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_left
    type: set_position
    position: 0
  - device_id: b964938e4137cac9e362d8e58c46735c
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_right
    type: set_position
    position: 0
  - device_id: 954f073b4ae1047e8c0eee6fafa2c966
    domain: cover
    entity_id: cover.ikea_kitchen_blind_right
    type: set_position
    position: 0
  mode: single
- id: '1644523825156'
  alias: Toggle Hallway Lamp when movement detected
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 5febaf7b28ca8fb29b2060f86befeeba
    entity_id: binary_sensor.aqara_mccgq11lm_front_door_contact
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 69ba0943a34913840f6ef4c6a74e6747
    entity_id: binary_sensor.aqara_rtcgq11lm_hallway_east_occupancy
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 7a44ce780b6a4d7c22eb945c1ffdaade
    entity_id: binary_sensor.aqara_rtcgq11lm_hallway_west_occupancy
    domain: binary_sensor
  condition:
  - condition: time
    after: '22:30:00'
    before: 05:30:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  - condition: device
    type: is_off
    device_id: 64cad46a7610b5987b7ffd884ba0e07a
    entity_id: light.ikea_hallway_lamp
    domain: light
  action:
  - type: turn_on
    device_id: 64cad46a7610b5987b7ffd884ba0e07a
    entity_id: light.ikea_hallway_lamp
    domain: light
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 64cad46a7610b5987b7ffd884ba0e07a
    entity_id: light.ikea_hallway_lamp
    domain: light
  mode: restart
- id: '1649616134986'
  alias: Enable zappi when car is at Home
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.tesla_geofence
    to: Home
  condition: []
  action:
  - device_id: 2c0e9c56ea1872756bd47a69f97d47c8
    domain: select
    entity_id: select.myenergi_zappi_charge_mode
    type: select_option
    option: Eco+
  mode: single
- id: '1649616618263'
  alias: Disable zappi when car leaves Home
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.tesla_geofence
    from: Home
  condition: []
  action:
  - device_id: 2c0e9c56ea1872756bd47a69f97d47c8
    domain: select
    entity_id: select.myenergi_zappi_charge_mode
    type: select_option
    option: Stopped
  mode: single
