alias: Trigger when downstairs boiler turns on
trigger:
  platform: state
  entity_id: climate.downstairs
action:
  service: script.notify_mqtt
  data_template:
    zone: downstairs
    mode: "{{ trigger.entity_id }}" # should be something like heating, idle