alias: Trigger when downstairs boiler turns on
trigger:
  platform: state
  entity_id: climate.downstairs
action:
  service: script.notify_mqtt
  data:
    zone: downstairs
    mode: heating # {{ trigger.platform }} # should be something like heating, idle