- id: '1613741702888'
  alias: Turn off lights after sunrise and open blinds
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: +00:15:00
  condition: []
  action:
  - type: turn_off
    device_id: 119baa3c1c324df38ebbb62778d02b90
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_off
    device_id: 78db16d7a5354c54059380ad65e6a005
    entity_id: light.ikea_kitchen_lamp
    domain: light
  - device_id: 794cd228824b84dfb5ad688ba82fbd0f
    domain: cover
    entity_id: cover.ikea_kitchen_blind_left
    type: set_position
    position: 100
  - device_id: 10dba2b49d0ac3d3d38895eadc2c04e0
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_left
    type: set_position
    position: 100
  - device_id: be1717a36a296b7fbf56912c145c6967
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_right
    type: set_position
    position: 100
  - device_id: a74bab6198d89faf5200af754b44b1e0
    domain: cover
    entity_id: cover.ikea_kitchen_blind_right
    type: set_position
    position: 100
  mode: single
- id: '1613741842726'
  alias: Turn off lights at bedtime
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: 119baa3c1c324df38ebbb62778d02b90
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_off
    device_id: 78db16d7a5354c54059380ad65e6a005
    entity_id: light.ikea_kitchen_lamp
    domain: light
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.ikea_e1603_e1702_control_outlet
    alias: Turn off Christmas Lights
    enabled: false
  mode: single
- id: '1613741995095'
  alias: Turn on lights and lower blinds at dusk
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:25:00
  condition: []
  action:
  - type: turn_on
    device_id: 119baa3c1c324df38ebbb62778d02b90
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_on
    device_id: 78db16d7a5354c54059380ad65e6a005
    entity_id: light.ikea_kitchen_lamp
    domain: light
  - device_id: 794cd228824b84dfb5ad688ba82fbd0f
    domain: cover
    entity_id: cover.ikea_kitchen_blind_left
    type: set_position
    position: 50
  - device_id: 10dba2b49d0ac3d3d38895eadc2c04e0
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_left
    type: set_position
    position: 50
  - device_id: be1717a36a296b7fbf56912c145c6967
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_right
    type: set_position
    position: 50
  - device_id: a74bab6198d89faf5200af754b44b1e0
    domain: cover
    entity_id: cover.ikea_kitchen_blind_right
    type: set_position
    position: 50
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.ikea_e1603_e1702_control_outlet
    alias: Turn on Christmas Lights
    enabled: false
  mode: single
- id: '1613742091259'
  alias: Turn on lights in the morning
  description: ''
  trigger:
  - platform: time
    at: 06:35
  - platform: time
    at: 07:30
  condition:
  - condition: sun
    before: sunrise
  - condition: or
    conditions:
    - condition: time
      after: 06:34
      weekday:
      - mon
      - tue
      - wed
    - condition: time
      after: 07:29
      weekday:
      - thu
      - fri
      - sat
      - sun
  action:
  - type: turn_on
    device_id: 119baa3c1c324df38ebbb62778d02b90
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_on
    device_id: 78db16d7a5354c54059380ad65e6a005
    entity_id: light.ikea_kitchen_lamp
    domain: light
    enabled: false
  mode: single
- id: '1614714623032'
  alias: Close blinds fully after sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:20:00
  condition: []
  action:
  - device_id: 794cd228824b84dfb5ad688ba82fbd0f
    domain: cover
    entity_id: cover.ikea_kitchen_blind_left
    type: set_position
    position: 0
  - device_id: 10dba2b49d0ac3d3d38895eadc2c04e0
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_left
    type: set_position
    position: 0
  - device_id: be1717a36a296b7fbf56912c145c6967
    domain: cover
    entity_id: cover.ikea_kitchen_blind_centre_right
    type: set_position
    position: 0
  - device_id: a74bab6198d89faf5200af754b44b1e0
    domain: cover
    entity_id: cover.ikea_kitchen_blind_right
    type: set_position
    position: 0
  mode: single
- id: '1644523825156'
  alias: Toggle Hallway Lamp when movement detected
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 4338933d0d6029f116c96d9efcdd435f
    entity_id: binary_sensor.aqara_mccgq11lm_front_door_contact
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 5b9399d7bb2213ace4609ea745288184
    entity_id: binary_sensor.aqara_rtcgq11lm_hallway_east_occupancy
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: bb473e18a2c6ea6b011a0f012d8b5f6d
    entity_id: binary_sensor.aqara_rtcgq11lm_hallway_west_occupancy
    domain: binary_sensor
  condition:
  - condition: time
    after: '22:30:00'
    before: 05:30:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - type: turn_on
    device_id: 119baa3c1c324df38ebbb62778d02b90
    entity_id: light.ikea_hallway_lamp
    domain: light
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 119baa3c1c324df38ebbb62778d02b90
    entity_id: light.ikea_hallway_lamp
    domain: light
  mode: restart
- id: '1649616134986'
  alias: Enable zappi when car is at Home
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.tesla_geofence
    to: Home
  condition: []
  action:
  - device_id: c86fcb9ca4a7bbc2d0adf158b54ac53c
    domain: select
    entity_id: select.myenergi_zappi_charge_mode
    type: select_option
    option: Eco+
  mode: single
- id: '1649616618263'
  alias: Disable zappi when car leaves Home
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.tesla_geofence
    from: Home
  condition: []
  action:
  - device_id: c86fcb9ca4a7bbc2d0adf158b54ac53c
    domain: select
    entity_id: select.myenergi_zappi_charge_mode
    type: select_option
    option: Stopped
  mode: single
- id: '1686078325150'
  alias: Set electricity metering to free
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - service: select.select_option
    data:
      option: free
    target:
      entity_id: select.daily_electricity
    alias: Set daily electricity option to free
  - service: select.select_option
    data:
      option: free
    target:
      entity_id: select.monthly_electricity
    alias: Set monthly electricity option to free
  - service: input_number.set_value
    data:
      value: 0
    target:
      entity_id: input_number.current_electricity_unit_price
    alias: Set current electricity price to 0
  mode: single
- id: '1686078384701'
  alias: Set electricity metering to fixed price
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - service: select.select_option
    data:
      option: fixed_price
    target:
      entity_id: select.daily_electricity
    alias: Set daily electricity meter to fixed
  - service: select.select_option
    data:
      option: fixed_price
    target:
      entity_id: select.monthly_electricity
    alias: Set monthly electricity meter to fixed
  - service: input_number.set_value
    data:
      value: 0.359
    target:
      entity_id: input_number.current_electricity_unit_price
    alias: Set current electricity price to 0.359
  mode: single
- id: '1693318905655'
  alias: Set TV Lights when Living Room TV starts playing
  description: ''
  trigger:
  - platform: device
    device_id: fbae520090d5b6aaad23951edb0a3272
    domain: media_player
    entity_id: 847b01da89d04eef8cb082c9b4811038
    type: playing
  - platform: device
    device_id: fbae520090d5b6aaad23951edb0a3272
    domain: media_player
    entity_id: 847b01da89d04eef8cb082c9b4811038
    type: paused
  - platform: device
    device_id: fbae520090d5b6aaad23951edb0a3272
    domain: media_player
    entity_id: 847b01da89d04eef8cb082c9b4811038
    type: turned_off
  - platform: device
    device_id: 55baabe3ec51b83808de81b2f6bfbf78
    domain: media_player
    entity_id: 88b4ad6fd627b7b4993254745ce54225
    type: turned_on
  condition:
  - condition: device
    device_id: 55baabe3ec51b83808de81b2f6bfbf78
    domain: media_player
    entity_id: 88b4ad6fd627b7b4993254745ce54225
    type: is_on
  action:
  - if:
    - condition: state
      entity_id: media_player.living_room_tv
      attribute: app_name
      state: Disney+
    - condition: device
      device_id: fbae520090d5b6aaad23951edb0a3272
      domain: media_player
      entity_id: 847b01da89d04eef8cb082c9b4811038
      type: is_playing
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.wled
    - service: select.select_option
      data:
        option: Disney+
      target:
        entity_id: select.wled_preset
    alias: Set Lights to Disney+ Preset When Playing
  - if:
    - condition: device
      device_id: fbae520090d5b6aaad23951edb0a3272
      domain: media_player
      entity_id: 847b01da89d04eef8cb082c9b4811038
      type: is_paused
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.wled
      alias: Turn On TV Lights
    - service: select.select_option
      data:
        option: Paused
      target:
        entity_id: select.wled_preset
      alias: Select "Paused" Preset
    alias: Set Lights to Paused Preset
  - if:
    - condition: device
      device_id: fbae520090d5b6aaad23951edb0a3272
      domain: media_player
      entity_id: 847b01da89d04eef8cb082c9b4811038
      type: is_off
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.wled
    - service: select.select_option
      data:
        option: Idle
      target:
        entity_id: select.wled_preset
    alias: Select 'Idle' Preset
  - if:
    - condition: state
      entity_id: media_player.living_room_tv
      attribute: app_name
      state: Paramount+
    - condition: device
      device_id: fbae520090d5b6aaad23951edb0a3272
      domain: media_player
      entity_id: 847b01da89d04eef8cb082c9b4811038
      type: is_playing
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.wled
    - service: select.select_option
      data:
        option: Paramount+
      target:
        entity_id: select.wled_preset
    alias: Set Lights to Paramount+ Preset When Playing
  - alias: Set Lights to AppleTV Preset When Playing
    if:
    - condition: state
      entity_id: media_player.living_room_tv
      attribute: app_name
      state: Apple TV
    - condition: device
      device_id: fbae520090d5b6aaad23951edb0a3272
      domain: media_player
      entity_id: 847b01da89d04eef8cb082c9b4811038
      type: is_playing
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.wled
    - service: select.select_option
      data:
        option: AppleTV
      target:
        entity_id: select.wled_preset
  - if:
    - condition: state
      entity_id: media_player.living_room_tv
      attribute: app_name
      state: Kodi
    - condition: device
      device_id: fbae520090d5b6aaad23951edb0a3272
      domain: media_player
      entity_id: 847b01da89d04eef8cb082c9b4811038
      type: is_playing
    then:
    - service: light.turn_on
      data: {}
      target:
        entity_id: light.wled
    - service: select.select_option
      data:
        option: Kodi
      target:
        entity_id: select.wled_preset
    alias: Set Lights to Kodi Preset When Playing
  mode: single
- id: '1693320967684'
  alias: Turn off TV lights when TV is turned off
  description: ''
  trigger:
  - platform: device
    device_id: 55baabe3ec51b83808de81b2f6bfbf78
    domain: media_player
    entity_id: 88b4ad6fd627b7b4993254745ce54225
    type: turned_off
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.wled
  mode: single
- id: '1701599131231'
  alias: Test temperature things
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.front_small_bedroom_temperature
    for:
      hours: 0
      minutes: 2
      seconds: 0
    below: 17
  condition: []
  action:
  - service: tts.google_say
    data:
      cache: false
      entity_id: media_player.kitchen
      message: Sam's bedroom is below 17 degrees
  mode: single
- id: '1703075760479'
  alias: Trigger actions if flood detected
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.shellies_flood_1_flood
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: tts.google_say
    data:
      cache: false
      entity_id: media_player.kitchen
      message: Flooding in the downstairs bathroom
  mode: single
