- id: '1613741702888'
  alias: Turn off lights after sunrise and open blinds
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: +00:20:00
  condition: []
  action:
  - domain: light
    entity_id: light.ikea_hallway_lamp
    device_id: ee04d6c564e267e69702eec44f2eb789
    type: turn_off
  - domain: light
    entity_id: light.ikea_kitchen_lamp
    device_id: 433637c9f1d8bad564b9c2be65ec6128
    type: turn_off
  - device_id: 26d75c5aab0ee48ff0fb91c994a4f147
    domain: cover
    entity_id: cover.0x680ae2fffe8c9cf8
    type: set_position
    position: 100
  - device_id: de7bc37e783453279aa5768585f25c44
    domain: cover
    entity_id: cover.0xec1bbdfffe985ebe
    type: set_position
    position: 100
  - device_id: b98ac8202850c420bc8dfaef6c557e09
    domain: cover
    entity_id: cover.0x680ae2fffe1c5c77
    type: set_position
    position: 100
  - device_id: 3d9a5c4652add742b19044a019c7142a
    domain: cover
    entity_id: cover.0x680ae2fffe1c3b8d
    type: set_position
    position: 100
  mode: single
- id: '1613741842726'
  alias: Turn off lights at bedtime
  description: ''
  trigger:
  - platform: time
    at: '22:30'
  condition: []
  action:
  - type: turn_off
    device_id: ee04d6c564e267e69702eec44f2eb789
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_off
    device_id: 433637c9f1d8bad564b9c2be65ec6128
    entity_id: light.ikea_kitchen_lamp
    domain: light
  mode: single
- id: '1613741995095'
  alias: Turn on lights and lower blinds at dusk
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:20:00
  condition: []
  action:
  - type: turn_on
    device_id: ee04d6c564e267e69702eec44f2eb789
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_on
    device_id: 433637c9f1d8bad564b9c2be65ec6128
    entity_id: light.ikea_kitchen_lamp
    domain: light
  - device_id: 26d75c5aab0ee48ff0fb91c994a4f147
    domain: cover
    entity_id: cover.0x680ae2fffe8c9cf8
    type: set_position
    position: 50
  - device_id: de7bc37e783453279aa5768585f25c44
    domain: cover
    entity_id: cover.0xec1bbdfffe985ebe
    type: set_position
    position: 50
  - device_id: b98ac8202850c420bc8dfaef6c557e09
    domain: cover
    entity_id: cover.0x680ae2fffe1c5c77
    type: set_position
    position: 50
  - device_id: 3d9a5c4652add742b19044a019c7142a
    domain: cover
    entity_id: cover.0x680ae2fffe1c3b8d
    type: set_position
    position: 50
  mode: single
- id: '1613742091259'
  alias: Turn on lights in the morning
  description: ''
  trigger:
  - platform: time
    at: 06:35
  - platform: time
    at: 07:30
  condition:
  - condition: sun
    before: sunrise
  - condition: or
    conditions:
    - condition: time
      after: 06:34
      weekday:
      - mon
      - tue
      - wed
    - condition: time
      after: 07:29
      weekday:
      - thu
      - fri
      - sat
      - sun
  action:
  - type: turn_on
    device_id: ee04d6c564e267e69702eec44f2eb789
    entity_id: light.ikea_hallway_lamp
    domain: light
  - type: turn_on
    device_id: 433637c9f1d8bad564b9c2be65ec6128
    entity_id: light.ikea_kitchen_lamp
    domain: light
  mode: single
- id: '1614714623032'
  alias: Close blinds fully after sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:20:00
  condition: []
  action:
  - device_id: 26d75c5aab0ee48ff0fb91c994a4f147
    domain: cover
    entity_id: cover.0x680ae2fffe8c9cf8
    type: set_position
    position: 0
  - device_id: de7bc37e783453279aa5768585f25c44
    domain: cover
    entity_id: cover.0xec1bbdfffe985ebe
    type: set_position
    position: 0
  - device_id: b98ac8202850c420bc8dfaef6c557e09
    domain: cover
    entity_id: cover.0x680ae2fffe1c5c77
    type: set_position
    position: 0
  - device_id: 3d9a5c4652add742b19044a019c7142a
    domain: cover
    entity_id: cover.0x680ae2fffe1c3b8d
    type: set_position
    position: 0
  mode: single
- id: '1644523825156'
  alias: Toggle Hallway Lamp when movement detected
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 38ebc198a4e836ee442c74f67e89c7e0
    entity_id: binary_sensor.aqara_rtcgq11lm_hallway_east_occupancy
    domain: binary_sensor
  - type: motion
    platform: device
    device_id: 88d6e788456c14204c36b155bb3bf251
    entity_id: binary_sensor.aqara_rtcgq11lm_hallway_west_occupancy
    domain: binary_sensor
  - type: opened
    platform: device
    device_id: 9912a42c9e699cb105d0edb11f51225d
    entity_id: binary_sensor.0x00158d000693b930_contact
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
  - condition: device
    type: is_off
    device_id: ee04d6c564e267e69702eec44f2eb789
    entity_id: light.ikea_hallway_lamp
    domain: light
  action:
  - type: turn_on
    device_id: ee04d6c564e267e69702eec44f2eb789
    entity_id: light.ikea_hallway_lamp
    domain: light
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: ee04d6c564e267e69702eec44f2eb789
    entity_id: light.ikea_hallway_lamp
    domain: light
  mode: restart
- id: '1649616134986'
  alias: Enable zappi when car is at Home
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.tesla_geofence
    to: Home
  condition: []
  action:
  - device_id: 64c9938af5d35c4d083b3c4c622b220c
    domain: select
    entity_id: select.myenergi_zappi_charge_mode
    type: select_option
    option: Eco+
  mode: single
- id: '1649616618263'
  alias: Disable zappi when car leaves Home
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.tesla_geofence
    from: Home
  condition: []
  action:
  - device_id: 64c9938af5d35c4d083b3c4c622b220c
    domain: select
    entity_id: select.myenergi_zappi_charge_mode
    type: select_option
    option: Stopped
  mode: single
