alias: Trigger when downstairs boiler turns on
trigger:
  platform: state
  entity_id: climate.downstairs
action:
  service: script.notify_mqtt
  data:
    target: "ember"
    message: "From {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"