title: Brompton
views:
  - path: overview
    title: Overview
    cards:
#      - type: vertical-stack
#        cards:
#          - type: weather-forecast
#            entity: weather.home
#          - type: glance
#            title: Outdoors
#            entities:
#              - entity: sensor.outside_temperature
#                name: Temperature
#              - entity: sensor.outside_humidity
#                name: Humidity
#              - entity: sensor.outside_pressure
#                name: Pressure
#              - entity: sensor.outside_lux
#                name: Light
#      - type: conditional
#        conditions:
#          - entity: person.david
#            state: "away"
#        card:
#          type: entities
#          entities:
#            - person.david
      - type: entities
        entities:
#          - media_player.living_room_tv_2
#          - media_player.living_room_tv
          - sensor.aqara_wsdcgq12lm_sitting_room_humidity
          - sensor.aqara_wsdcgq12lm_sitting_room_temperature
          - binary_sensor.aqara_rtcgq11lm_sitting_room_occupancy
          - media_player.kodi_f531f7696570fce9556ffa955ce7a3b3
        title: Sitting Room
        show_header_toggle: false
      - type: vertical-stack
        cards:
#        - type: map
#          entities:
#            -
        - type: entities
          title: Car
          entities:
            - sensor.tesla_state
            - sensor.tesla_geofence
            - sensor.tesla_speed
            - sensor.tesla_power
            - sensor.tesla_elevation
            - sensor.tesla_inside_temp
            - sensor.tesla_outside_temp
            - sensor.tesla_odometer
            - sensor.tesla_est_battery_range_km
            - sensor.tesla_usable_battery_level
            - sensor.tesla_charge_energy_added
            - sensor.tesla_time_to_full_charge
            - binary_sensor.tesla_locked
            - binary_sensor.tesla_sentry_mode
            - binary_sensor.tesla_windows_open
            - binary_sensor.tesla_doors_open
            - binary_sensor.tesla_boot_open
            - binary_sensor.tesla_frunk_open
            - binary_sensor.tesla_is_user_present
            - binary_sensor.tesla_is_climate_on
            - binary_sensor.tesla_is_preconditioning
            - binary_sensor.tesla_plugged_in
            - binary_sensor.tesla_charge_port_door_open
      - type: entities
        entities:
          - light.ikea_hallway_lamp
          - sensor.aqara_wsdcgq12lm_hallway_temperature
          - sensor.aqara_wsdcgq12lm_hallway_humidity
          - binary_sensor.aqara_mccgq11lm_front_door_contact
          - binary_sensor.aqara_rtcgq11lm_hallway_east_occupancy
          - binary_sensor.aqara_rtcgq11lm_hallway_west_occupancy
        title: Hallway
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.aqara_wsdcgq12lm_downstairs_toilet_temperature
          - sensor.aqara_wsdcgq12lm_downstairs_toilet_humidity
        title: Downstairs Toilet
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.aqara_wsdcgq12lm_utility_room_temperature
          - sensor.aqara_wsdcgq12lm_utility_room_humidity
          - binary_sensor.aqara_mccgq11lm_garage_door_contact
        title: Utility Room
        show_header_toggle: false

  - title: Kitchen
    path: kitchen
    cards:
      - type: media-control
        entity: media_player.kitchen
      - type: entities
        entities:
          - type: section
            label: Lights
          - light.ikea_kitchen_lamp
          - type: section
            label: Blinds
          - cover.ikea_kitchen_blind_left
          - cover.ikea_kitchen_blind_centre_left
          - cover.ikea_kitchen_blind_centre_right
          - cover.ikea_kitchen_blind_right
          - type: section
            label: Environment
          - sensor.aqara_wsdcgq12lm_kitchen_extension_temperature
          - sensor.aqara_wsdcgq12lm_kitchen_extension_humidity
          - sensor.aqara_wsdcgq12lm_kitchen_main_temperature
          - sensor.aqara_wsdcgq12lm_kitchen_main_humidity
          - sensor.aqara_wsdcgq12lm_kitchen_snug_temperature
          - sensor.aqara_wsdcgq12lm_kitchen_snug_humidity
          - type: section
            label: Doors
          - binary_sensor.aqara_mccgq11lm_kitchen_main_back_door_contact
          - binary_sensor.aqara_mccgq11lm_kitchen_secondary_back_door_contact
        show_header_toggle: false

  - title: Sitting Room
    path: sitting-room

  - title: Upstairs
    path: upstairs
    cards:
      - type: title
        entity: sensor.front_big_bedroom_temperature
      - type: entities
        entities:
          - sensor.front_big_bedroom_temperature
          - sensor.front_big_bedroom_humidity
        title: Ellen & David's Bedroom
        show_header_toggle: false
        footer:
          type: graph
          entity: sensor.front_big_bedroom_temperature
          hours_to_show: 24
          detail: 2
      - type: entities
        entities:
          - sensor.front_small_bedroom_temperature
          - sensor.front_small_bedroom_humidity
        title: Sam's Bedroom
        show_header_toggle: false
        footer:
          type: graph
          entity: sensor.front_small_bedroom_temperature
          hours_to_show: 24
          detail: 2
      - type: entities
        entities:
          - sensor.back_small_bedroom_temperature
          - sensor.back_small_bedroom_humidity
        title: Joey's Bedroom
        show_header_toggle: false
        footer:
          type: graph
          entity: sensor.back_small_bedroom_temperature
          hours_to_show: 24
          detail: 2
      - type: entities
        entities:
          - sensor.back_big_bedroom_temperature
          - sensor.back_big_bedroom_humidity
        title: Spare Bedroom
        show_header_toggle: false
        footer:
          type: graph
          entity: sensor.back_big_bedroom_temperature
          hours_to_show: 24
          detail: 2
      - type: entities
        entities:
            - entity: sensor.upstairs_bathroom_temperature
            - entity: sensor.upstairs_bathroom_humidity
        title: Upstairs Bathroom
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.upstairs_landing_temperature
          - sensor.upstairs_landing_humidity
        title: Upstairs
        show_header_toggle: false
      - type: entities
        entities:
          - entity: sensor.top_of_hot_water_tank_temperature
            name: Top of Tank
          - entity: sensor.bottom_of_hot_water_tank_temperature
            name: Bottom of Tank
        title: Hot Water
        show_header_toggle: false