title: Brompton
views:
  - path: overview
    title: Overview
    cards:
      - type: weather-forecast
        entity: weather.home
      - type: energy-distribution
        link_dashboard: true
      - type: entity
        entity: alarm_control_panel.8124_b17_zone_1_alarm
        name: Alarm
        state_color: true
      - type: grid
        title: Electricity
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.daily_electricity_cost
                name: Today
              - type: tile
                entity: sensor.monthly_electricity_cost
                name: This Month
      - type: grid
        title: Car
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.tesla_est_battery_range_km
              - type: tile
                entity: sensor.tesla_usable_battery_level
          - type: conditional
            conditions:
              - entity: sensor.tesla_state
                state: "charging"
            card:
              type: tile
              entity: sensor.tesla_time_to_full_charge
              icon: mdi:ev-plug-ccs2
              color: light-green
          - type: conditional
            conditions:
              - entity: sensor.tesla_state
                state: "driving"
            card:
              type: tile
              entity: sensor.tesla_state
          - type: horizontal-stack
            cards:
              - type: tile
                entity: binary_sensor.tesla_locked
              - type: tile
                entity: binary_sensor.tesla_sentry_mode

  - title: Kitchen
    path: kitchen
    cards:
      - type: grid
        title: Blinds
        columns: 1
        square: false
        cards:
          - type: vertical-stack
            cards:
              - type: tile
                entity: cover.ikea_kitchen_blind_left
                features:
                  - type: "cover-open-close"
              - type: entity-filter
                show_empty: false
                entities:
                  - sensor.ikea_kitchen_blind_left_battery
                state_filter:
                  - operator: "<="
                    value: 20
              - type: tile
                entity: cover.ikea_kitchen_blind_centre_left
                features:
                  - type: "cover-open-close"
              - type: entity-filter
                show_empty: false
                card:
                  type: tile
                entities:
                  - sensor.ikea_kitchen_blind_centre_left_battery
                state_filter:
                  - operator: "<="
                    value: 20
              - type: tile
                entity: cover.ikea_kitchen_blind_centre_right
                features:
                  - type: "cover-open-close"
              - type: tile
                entity: cover.ikea_kitchen_blind_right
                features:
                  - type: "cover-open-close"
      - type: grid
        title: Lights
        columns: 1
        square: false
        cards:
          - type: tile
            entity: light.ikea_kitchen_lamp
            features:
              - type: "light-brightness"
      - type: grid
        title: Media
        columns: 1
        square: false
        cards:
          - type: media-control
            entity: media_player.kitchen
      - type: grid
        title: Environment
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.aqara_wsdcgq12lm_kitchen_extension_temperature
                name: Extension
              - type: tile
                entity: sensor.aqara_wsdcgq12lm_kitchen_extension_humidity
                name: Extension
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.aqara_wsdcgq12lm_kitchen_main_temperature
                name: Main
              - type: tile
                entity: sensor.aqara_wsdcgq12lm_kitchen_main_humidity
                name: Main
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.aqara_wsdcgq12lm_kitchen_snug_temperature
                name: Snug
              - type: tile
                entity: sensor.aqara_wsdcgq12lm_kitchen_snug_humidity
                name: Snug
      - type: grid
        title: Doors
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: binary_sensor.0x00158d000693b91b_contact
              - type: tile
                entity: binary_sensor.aqara_mccgq11lm_kitchen_secondary_back_door_contact

  - title: Sitting Room
    path: sitting-room
    cards:
      - type: grid
        title: Media
        columns: 1
        square: false
        cards:
          - type: media-control
            entity: media_player.tv
          - type: media-control
            entity: media_player.living_room_tv
          - type: media-control
            entity: media_player.living_room
      - type: grid
        title: Lights
        columns: 1
        square: false
        cards:
          - type: tile
            entity: light.wled
            features:
              - type: "light-brightness"
      - type: grid
        title: Environment
        columns: 1
        square: false
        cards:
          - type: tile
            entity: sensor.aqara_wsdcgq12lm_sitting_room_temperature
          - type: tile
            entity: sensor.aqara_wsdcgq12lm_sitting_room_humidity
          - type: tile
            entity: binary_sensor.aqara_rtcgq11lm_sitting_room_occupancy

  - title: Downstairs
    path: downstairs
    cards:
      - type: grid
        title: Hallway
        columns: 1
        square: false
        cards:
          - type: tile
            entity: light.ikea_hallway_lamp
          - type: tile
            entity: sensor.aqara_wsdcgq12lm_hallway_temperature
          - type: tile
            entity: sensor.aqara_wsdcgq12lm_hallway_humidity
          - type: tile
            entity: binary_sensor.aqara_mccgq11lm_front_door_contact
          - type: tile
            entity: binary_sensor.aqara_rtcgq11lm_hallway_east_occupancy
          - type: tile
            entity: binary_sensor.aqara_rtcgq11lm_hallway_west_occupancy
      - type: grid
        title: Downstairs Toilet
        columns: 1
        square: false
        cards:
          - type: tile
            entity: sensor.aqara_wsdcgq12lm_downstairs_toilet_temperature
          - type: tile
            entity: sensor.aqara_wsdcgq12lm_downstairs_toilet_humidity
      - type: grid
        title: Utility Room
        columns: 1
        square: false
        cards:
          - type: tile
            entity: sensor.aqara_wsdcgq12lm_utility_room_temperature
          - type: tile
            entity: sensor.aqara_wsdcgq12lm_utility_room_humidity
          - type: tile
            entity: binary_sensor.aqara_mccgq11lm_garage_door_contact

  - title: Upstairs
    path: upstairs
    cards:
      - type: grid
        title: Ellen & David's Bedroom
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.front_big_bedroom_temperature
              - type: tile
                entity: sensor.front_big_bedroom_humidity
      - type: grid
        title: Sam's Bedroom
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.front_small_bedroom_temperature
              - type: tile
                entity: sensor.front_small_bedroom_humidity
      - type: grid
        title: Joey's Bedroom
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.back_small_bedroom_temperature
              - type: tile
                entity: sensor.back_small_bedroom_humidity
      - type: grid
        title: Spare Bedroom
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.back_big_bedroom_temperature
              - type: tile
                entity: sensor.back_big_bedroom_humidity
      - type: grid
        title: Bathroom
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.upstairs_bathroom_temperature
              - type: tile
                entity: sensor.upstairs_bathroom_humidity
      - type: grid
        title: Landing
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.upstairs_landing_temperature
              - type: tile
                entity: sensor.upstairs_landing_humidity
      - type: grid
        title: Hot Water
        columns: 1
        square: false
        cards:
          - type: horizontal-stack
            cards:
              - type: tile
                entity: sensor.top_of_hot_water_tank_temperature
                name: Top of Tank
              - type: tile
                entity: sensor.bottom_of_hot_water_tank_temperature
                name: Bottom of Tank