title: Brompton
views:
  - path: overview
    title: Overview
    cards:
      - type: sensor
        entity: sensor.front_big_bedroom_temperature
        name: Test
        graph: line
        unit: '°C'
      - type: entities
        entities:
          - sensor.front_big_bedroom_temperature
          - sensor.front_big_bedroom_humidity
          - sensor.front_big_bedroom_pressure
        title: Front Big Bedroom
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.front_small_bedroom_temperature
          - sensor.front_small_bedroom_humidity
          - sensor.front_small_bedroom_pressure
        title: Front Small Bedroom
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.back_big_bedroom_temperature
          - sensor.back_big_bedroom_humidity
          - sensor.back_big_bedroom_pressure
        title: Back Big Bedroom
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.back_small_bedroom_temperature
          - sensor.back_small_bedroom_humidity
          - sensor.back_small_bedroom_pressure
        title: Back Small Bedroom
        show_header_toggle: false
      - type: entities
        entities:
          - light.ikea_kitchen_lamp
          - cover.0x680ae2fffe1c5c77
          - cover.0x680ae2fffe8c9cf8
          - cover.0xec1bbdfffe985ebe
          - cover.0x680ae2fffe1c3b8d
          - media_player.kitchen
          - sensor.0x00158d0006a03a86_humidity
          - sensor.0x00158d0006a03a86_temperature
          - sensor.0x00158d0006a03a86_pressure
          - sensor.0x00158d0006a03ae5_humidity
          - sensor.0x00158d0006a03ae5_temperature
          - sensor.0x00158d0006a03ae5_pressure
          - sensor.0x00158d000693a944_humidity
          - sensor.0x00158d000693a944_temperature
          - sensor.0x00158d000693a944_pressure
          - binary_sensor.0x00158d000693b91b_contact
          - binary_sensor.0x00158d00068b8581_contact
        title: Kitchen
        show_header_toggle: false
      - type: entities
        entities:
          - media_player.living_room_tv
          - sensor.aqara_wsdcgq12lm_sitting_room_humidity
          - sensor.aqara_wsdcgq12lm_sitting_room_temperature
          - sensor.aqara_wsdcgq12lm_sitting_room_pressure
          - binary_sensor.0x00158d0006a15847_occupancy
        title: Sitting Room
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.upstairs_landing_temperature
          - sensor.upstairs_landing_humidity
          - sensor.upstairs_landing_pressure
          - entity: climate.upstairs
            name: Heating
        title: Upstairs
        show_header_toggle: false
      - type: map
        entities:
          - entity: person.person_david
            name: David
          - entity: zone.home
        title: Test Map
        default_zoom: 16
        hours_to_show: 48
        show_header_toggle: false
      - type: entities
        entities:
          - entity: sensor.upstairs_bathroom_temperature
          - entity: sensor.upstairs_bathroom_humidity
          - entity: sensor.upstairs_bathroom_pressure
        title: Upstairs Bathroom
        show_header_toggle: false
      - type: entities
        entities:
          - light.ikea_hallway_lamp
          - sensor.0x00158d00068b7170_temperature
          - sensor.0x00158d00068b7170_humidity
          - sensor.0x00158d00068b7170_pressure
          - binary_sensor.0x00158d000693b930_contact
          - entity: climate.downstairs
            name: Heating
        title: Hallway
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.0x00158d00068b92eb_temperature
          - sensor.0x00158d00068b92eb_humidity
          - sensor.0x00158d00068b92eb_pressure
        title: Downstairs Toilet
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.0x00158d00067955d5_temperature
          - sensor.0x00158d00067955d5_humidity
          - sensor.0x00158d00067955d5_pressure
          - binary_sensor.0x00158d00068b85c8_contact
        title: Utility Room
        show_header_toggle: false
      - type: entities
        entities:
          - entity: climate.hot_water
            name: Heating
          - entity: sensor.top_of_hot_water_tank_temperature
            name: Top of Tank
          - entity: sensor.bottom_of_hot_water_tank_temperature
            name: Bottom of Tank
        title: Hot Water
        show_header_toggle: false

  - title: Downstairs
    path: downstairs
    cards:
      - type: light
        entity: light.ikea_hallway_lamp

  - title: Upstairs
    path: upstairs

  - title: Climate
    path: climate
    cards:
      - type: thermostat
        entity: climate.downstairs
        name: Downstairs
      - type: thermostat
        entity: climate.upstairs
        name: Upstairs
      - type: thermostat
        entity: climate.hot_water
        name: Hot Water

  - title: Outside
    path: outside
    cards:
      - type: entities
        entities:
          - sensor.outside_temperature
          - sensor.outside_humidity
          - sensor.outside_pressure
          - sensor.outside_lux
          - sensor.outside_pm_1_0
          - sensor.outside_pm_2_5
          - sensor.outside_pm_10_0
        title: Climate
        show_header_toggle: false