homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

weather:

# Enables the frontend
frontend:

# Enables configuration UI
config:

energy:

recorder:
  db_url: !secret recorder_db_url
  auto_purge: true
  purge_keep_days: 10
  exclude:
    entities:
      - sensor.last_boot
    entity_globs:
      - sensor.*_linkquality
      - sensor.*_voltage

influxdb:
  api_version: 2
  ssl: false
  host: "localhost"
  port: 8086
  token: !secret influxdb_token
  organization: dashford
  bucket: brompton

system_health:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

mqtt:
  broker: 10.243.0.100
  discovery: true
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enables a map showing the location of tracked devices
map:

zone:
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 150
    icon: mdi:home
  - name: David Work
    latitude: !secret zone_david_work_latitude
    longitude: !secret zone_david_work_longitude
    radius: 150
    icon: mdi:briefcase

#device_tracker:
#  - platform: luci
#    host: 192.168.1.1
#    username: !secret router_username
#    password: !secret router_password

# Track the sun
sun:

# Sensors
# TODO move into own sensor.yaml
sensor:
  - platform: mqtt
    state_topic: 'brompton/front-big-bedroom/temperature'
    name: 'Front Big Bedroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/front-big-bedroom/humidity'
    name: 'Front Big Bedroom Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/front-big-bedroom/pressure'
    name: 'Front Big Bedroom Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/front-small-bedroom/temperature'
    name: 'Front Small Bedroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/front-small-bedroom/humidity'
    name: 'Front Small Bedroom Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/front-small-bedroom/pressure'
    name: 'Front Small Bedroom Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/back-big-bedroom/temperature'
    name: 'Back Big Bedroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/back-big-bedroom/humidity'
    name: 'Back Big Bedroom Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/back-big-bedroom/pressure'
    name: 'Back Big Bedroom Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/back-small-bedroom/temperature'
    name: 'Back Small Bedroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/back-small-bedroom/humidity'
    name: 'Back Small Bedroom Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/back-small-bedroom/pressure'
    name: 'Back Small Bedroom Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-landing/temperature'
    name: 'Upstairs Landing Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-landing/humidity'
    name: 'Upstairs Landing Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-landing/pressure'
    name: 'Upstairs Landing Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-bathroom/temperature'
    name: 'Upstairs Bathroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-bathroom/humidity'
    name: 'Upstairs Bathroom Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-bathroom/pressure'
    name: 'Upstairs Bathroom Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/hot-water-tank/top/temperature'
    name: 'Top of Hot Water Tank Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/hot-water-tank/bottom/temperature'
    name: 'Bottom of Hot Water Tank Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/temperature'
    name: 'Outside Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/pressure'
    name: 'Outside Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/humidity'
    name: 'Outside Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/lux'
    name: 'Outside Lux'
    unit_of_measurement: 'lm'
    value_template: '{{ value_json.lux | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/particulate_matter/1.0'
    name: 'Outside PM 1.0'
    unit_of_measurement: 'μg/m³'
    value_template: '{{ value_json.pm | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/particulate_matter/2.5'
    name: 'Outside PM 2.5'
    unit_of_measurement: 'μg/m³'
    value_template: '{{ value_json.pm | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/particulate_matter/10.0'
    name: 'Outside PM 10.0'
    unit_of_measurement: 'μg/m³'
    value_template: '{{ value_json.pm | round(3) }}'
  - platform: mqtt
    name: tesla_state
    state_topic: "teslamate/cars/1/state"
    icon: mdi:car-connected
  - platform: mqtt
    name: tesla_geofence
    state_topic: "teslamate/cars/1/geofence"
    icon: mdi:earth
  - platform: mqtt
    name: tesla_latitude
    state_topic: "teslamate/cars/1/latitude"
    unit_of_measurement: °
    icon: mdi:crosshairs-gps
  - platform: mqtt
    name: tesla_longitude
    state_topic: "teslamate/cars/1/longitude"
    unit_of_measurement: °
    icon: mdi:crosshairs-gps
  - platform: mqtt
    name: tesla_shift_state
    state_topic: "teslamate/cars/1/shift_state"
    icon: mdi:car-shift-pattern
  - platform: mqtt
    name: tesla_speed
    state_topic: "teslamate/cars/1/speed"
    unit_of_measurement: "km/h"
    icon: mdi:speedometer
  - platform: mqtt
    name: tesla_power
    state_topic: "teslamate/cars/1/power"
    device_class: power
    unit_of_measurement: W
    icon: mdi:flash
  - platform: mqtt
    name: tesla_elevation
    state_topic: "teslamate/cars/1/elevation"
    unit_of_measurement: m
    icon: mdi:image-filter-hdr
  - platform: mqtt
    name: tesla_inside_temp
    state_topic: "teslamate/cars/1/inside_temp"
    device_class: temperature
    unit_of_measurement: °C
    icon: mdi:thermometer-lines
  - platform: mqtt
    name: tesla_outside_temp
    state_topic: "teslamate/cars/1/outside_temp"
    device_class: temperature
    unit_of_measurement: °C
    icon: mdi:thermometer-lines
  - platform: mqtt
    name: tesla_odometer
    state_topic: "teslamate/cars/1/odometer"
    unit_of_measurement: km
    icon: mdi:counter
  - platform: mqtt
    name: tesla_est_battery_range_km
    state_topic: "teslamate/cars/1/est_battery_range_km"
    unit_of_measurement: km
    icon: mdi:gauge
  - platform: mqtt
    name: tesla_usable_battery_level
    state_topic: "teslamate/cars/1/usable_battery_level"
    unit_of_measurement: "%"
    icon: mdi:battery-80
  - platform: mqtt
    name: tesla_charge_energy_added
    state_topic: "teslamate/cars/1/charge_energy_added"
    device_class: energy
    unit_of_measurement: kWh
    icon: mdi:battery-charging
  - platform: mqtt
    name: tesla_charger_actual_current
    state_topic: "teslamate/cars/1/charger_actual_current"
    device_class: current
    unit_of_measurement: A
    icon: mdi:lightning-bolt
  - platform: mqtt
    name: tesla_charger_power
    state_topic: "teslamate/cars/1/charger_power"
    device_class: power
    unit_of_measurement: kW
    icon: mdi:lightning-bolt
  - platform: mqtt
    name: tesla_time_to_full_charge
    state_topic: "teslamate/cars/1/time_to_full_charge"
    unit_of_measurement: h
    icon: mdi:clock-outline

binary_sensor:
  - platform: mqtt
    name: tesla_healthy
    state_topic: "teslamate/cars/1/healthy"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:heart-pulse
  - platform: mqtt
    name: tesla_update_available
    state_topic: "teslamate/cars/1/update_available"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:alarm
  - platform: mqtt
    name: tesla_locked
    device_class: lock
    state_topic: "teslamate/cars/1/locked"
    payload_on: "false"
    payload_off: "true"
  - platform: mqtt
    name: tesla_sentry_mode
    state_topic: "teslamate/cars/1/sentry_mode"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:cctv
  - platform: mqtt
    name: tesla_windows_open
    device_class: window
    state_topic: "teslamate/cars/1/windows_open"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:car-door
  - platform: mqtt
    name: tesla_doors_open
    device_class: door
    state_topic: "teslamate/cars/1/doors_open"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:car-door
  - platform: mqtt
    name: tesla_boot_open
    device_class: opening
    state_topic: "teslamate/cars/1/trunk_open"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:car-side
  - platform: mqtt
    name: tesla_frunk_open
    device_class: opening
    state_topic: "teslamate/cars/1/frunk_open"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:car-side
  - platform: mqtt
    name: tesla_is_user_present
    device_class: presence
    state_topic: "teslamate/cars/1/is_user_present"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:human-greeting
  - platform: mqtt
    name: tesla_is_climate_on
    state_topic: "teslamate/cars/1/is_climate_on"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:fan
  - platform: mqtt
    name: tesla_is_preconditioning
    state_topic: "teslamate/cars/1/is_preconditioning"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:fan
  - platform: mqtt
    name: tesla_plugged_in
    device_class: plug
    state_topic: "teslamate/cars/1/plugged_in"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:ev-station
  - platform: mqtt
    name: tesla_charge_port_door_open
    device_class: opening
    state_topic: "teslamate/cars/1/charge_port_door_open"
    payload_on: "true"
    payload_off: "false"
    icon: mdi:ev-plug-tesla

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

sonos:

lovelace:
  mode: storage
  dashboards:
    brompton-dashboard:
      mode: yaml
      title: Brompton
      icon: mdi:script
      show_in_sidebar: true
      filename: brompton.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
