homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

energy:

system_health:

influxdb:
  api_version: 1
  host: 192.168.1.10
  port: 8086
  database: home_assistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  ssl: false

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

mqtt:
  broker: 192.168.1.10
  discovery: true
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enables a map showing the location of tracked devices
map:

zone:
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 150
    icon: mdi:home
  - name: David Work
    latitude: !secret zone_david_work_latitude
    longitude: !secret zone_david_work_longitude
    radius: 150
    icon: mdi:briefcase

device_tracker:
  - platform: luci
    host: 192.168.1.1
    username: !secret router_username
    password: !secret router_password

# Track the sun
sun:

# Sensors
# TODO move into own sensor.yaml
sensor:
  - platform: mqtt
    state_topic: 'brompton/front-big-bedroom/temperature'
    name: 'Front Big Bedroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/front-big-bedroom/humidity'
    name: 'Front Big Bedroom Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/front-big-bedroom/pressure'
    name: 'Front Big Bedroom Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/front-small-bedroom/temperature'
    name: 'Front Small Bedroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/front-small-bedroom/humidity'
    name: 'Front Small Bedroom Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/front-small-bedroom/pressure'
    name: 'Front Small Bedroom Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/back-big-bedroom/temperature'
    name: 'Back Big Bedroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/back-big-bedroom/humidity'
    name: 'Back Big Bedroom Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/back-big-bedroom/pressure'
    name: 'Back Big Bedroom Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/back-small-bedroom/temperature'
    name: 'Back Small Bedroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/back-small-bedroom/humidity'
    name: 'Back Small Bedroom Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/back-small-bedroom/pressure'
    name: 'Back Small Bedroom Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-landing/temperature'
    name: 'Upstairs Landing Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-landing/humidity'
    name: 'Upstairs Landing Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-landing/pressure'
    name: 'Upstairs Landing Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-bathroom/temperature'
    name: 'Upstairs Bathroom Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-bathroom/humidity'
    name: 'Upstairs Bathroom Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/upstairs-bathroom/pressure'
    name: 'Upstairs Bathroom Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/hot-water-tank/top/temperature'
    name: 'Top of Hot Water Tank Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/hot-water-tank/bottom/temperature'
    name: 'Bottom of Hot Water Tank Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/temperature'
    name: 'Outside Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/pressure'
    name: 'Outside Pressure'
    unit_of_measurement: 'hPa'
    value_template: '{{ value_json.pressure | round(2) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/humidity'
    name: 'Outside Humidity'
    unit_of_measurement: '%RH'
    value_template: '{{ value_json.humidity | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/lux'
    name: 'Outside Lux'
    unit_of_measurement: 'lm'
    value_template: '{{ value_json.lux | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/particulate_matter/1.0'
    name: 'Outside PM 1.0'
    unit_of_measurement: 'μg/m³'
    value_template: '{{ value_json.pm | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/particulate_matter/2.5'
    name: 'Outside PM 2.5'
    unit_of_measurement: 'μg/m³'
    value_template: '{{ value_json.pm | round(3) }}'
  - platform: mqtt
    state_topic: 'brompton/outside/particulate_matter/10.0'
    name: 'Outside PM 10.0'
    unit_of_measurement: 'μg/m³'
    value_template: '{{ value_json.pm | round(3) }}'

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

sonos:

lovelace:
  mode: storage
  dashboards:
    brompton-dashboard:
      mode: yaml
      title: Brompton
      icon: mdi:script
      show_in_sidebar: true
      filename: brompton.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
