homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  country: !secret country

weather:

# Enables the frontend
frontend:

default_config:

# Enables configuration UI
config:

energy:

utility_meter:
  daily_electricity:
    source: sensor.myenergi_hub_grid_import_today
    unique_id: daily_electricity
    name: Daily
    cycle: daily
    tariffs:
      - fixed_price
      - free
  monthly_electricity:
    source: sensor.myenergi_hub_grid_import_today
    unique_id: monthly_electricity
    name: Monthly
    cycle: monthly
    tariffs:
      - fixed_price
      - free
input_text:
  electricity_fixed_price_tariff:
    name: Electricity Price per kWh (fixed)
    icon: mdi:cash
    initial: 0.4358
  electricity_free_tariff:
    name: Electricity Price per kWh (free)
    icon: mdi:cash
    initial: 0.00

template:
  - sensor:
      - name: "Daily Electricity Cost"
        unit_of_measurement: "Eur"
        icon: mdi:cash
        device_class: monetary
        state: "{{ (states('input_text.electricity_fixed_price_tariff')|float) * (states('sensor.daily_electricity_fixed_price')|float) + (states('input_text.electricity_free_tariff')|float) * (states('sensor.daily_electricity_free')|float) }}"

climate:
  - platform: ephember
    username: !secret ephember_username
    password: !secret ephember_password

recorder:
  db_url: !secret recorder_db_url
  auto_purge: true
  purge_keep_days: 10
  exclude:
    entities:
      - sensor.last_boot
    entity_globs:
      - sensor.*_linkquality
      - sensor.*_voltage

influxdb:
  api_version: 2
  ssl: false
  host: "localhost"
  port: 8086
  token: !secret influxdb_token
  organization: dashford
  bucket: brompton

system_health:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

mqtt:
  binary_sensor:
    - name: tesla_healthy
      state_topic: "teslamate/cars/1/healthy"
      unique_id: "teslamate-cars-1-healthy"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:heart-pulse
    - name: tesla_update_available
      state_topic: "teslamate/cars/1/update_available"
      unique_id: "teslamate-cars-1-update-available"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:alarm
    - name: tesla_locked
      device_class: lock
      state_topic: "teslamate/cars/1/locked"
      unique_id: "teslamate-cars-1-locked"
      payload_on: "false"
      payload_off: "true"
    - name: tesla_sentry_mode
      state_topic: "teslamate/cars/1/sentry_mode"
      unique_id: "teslamate-cars-1-sentry-mode"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:cctv
    - name: tesla_windows_open
      device_class: window
      state_topic: "teslamate/cars/1/windows_open"
      unique_id: "teslamate-cars-1-windows-open"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:car-door
    - name: tesla_doors_open
      device_class: door
      state_topic: "teslamate/cars/1/doors_open"
      unique_id: "teslamate-cars-1-doors-open"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:car-door
    - name: tesla_boot_open
      device_class: opening
      state_topic: "teslamate/cars/1/trunk_open"
      unique_id: "teslamate-cars-1-boot-open"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:car-side
    - name: tesla_frunk_open
      device_class: opening
      state_topic: "teslamate/cars/1/frunk_open"
      unique_id: "teslamate-cars-1-frunk-open"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:car-side
    - name: tesla_is_user_present
      device_class: presence
      state_topic: "teslamate/cars/1/is_user_present"
      unique_id: "teslamate-cars-1-user-present"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:human-greeting
    - name: tesla_is_climate_on
      state_topic: "teslamate/cars/1/is_climate_on"
      unique_id: "teslamate-cars-1-climate-on"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:fan
    - name: tesla_is_preconditioning
      state_topic: "teslamate/cars/1/is_preconditioning"
      unique_id: "teslamate-cars-1-preconditioning"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:fan
    - name: tesla_plugged_in
      device_class: plug
      state_topic: "teslamate/cars/1/plugged_in"
      unique_id: "teslamate-cars-1-plugged-in"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:ev-station
    - name: tesla_charge_port_door_open
      device_class: opening
      state_topic: "teslamate/cars/1/charge_port_door_open"
      unique_id: "teslamate-cars-1-charge-door-open"
      payload_on: "true"
      payload_off: "false"
      icon: mdi:ev-plug-ccs2
  sensor:
    - name: "Front Big Bedroom Temperature"
      state_topic: "brompton/front-big-bedroom/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      unique_id: "front-big-bedroom-temperature"
      value_template: "{{ value_json.temperature | round(2) }}"
    - name: "Front Big Bedroom Humidity"
      state_topic: "brompton/front-big-bedroom/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      unique_id: "front-big-bedroom-humidity"
      value_template: "{{ value_json.humidity | round(3) }}"
    - name: "Front Small Bedroom Temperature"
      state_topic: "brompton/front-small-bedroom/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      unique_id: "front-small-bedroom-temperature"
      value_template: "{{ value_json.temperature | round(2) }}"
    - name: "Front Small Bedroom Humidity"
      state_topic: "brompton/front-small-bedroom/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      unique_id: "front-small-bedroom-humidity"
      value_template: "{{ value_json.humidity | round(3) }}"
    - name: "Back Big Bedroom Temperature"
      state_topic: "brompton/back-big-bedroom/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      unique_id: "back-big-bedroom-temperature"
      value_template: "{{ value_json.temperature | round(2) }}"
    - name: "Back Big Bedroom Humidity"
      state_topic: "brompton/back-big-bedroom/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      unique_id: "back-big-bedroom-humidity"
      value_template: "{{ value_json.humidity | round(3) }}"
    - name: "Back Small Bedroom Temperature"
      state_topic: "brompton/back-small-bedroom/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      unique_id: "back-small-bedroom-temperature"
      value_template: "{{ value_json.temperature | round(2) }}"
    - name: "Back Small Bedroom Humidity"
      state_topic: "brompton/back-small-bedroom/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      unique_id: "back-small-bedroom-humidity"
      value_template: "{{ value_json.humidity | round(3) }}"
    - name: "Upstairs Landing Temperature"
      state_topic: "brompton/upstairs-landing/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      unique_id: "upstairs-landing-temperature"
      value_template: "{{ value_json.temperature | round(2) }}"
    - name: "Upstairs Landing Humidity"
      state_topic: "brompton/upstairs-landing/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      unique_id: "upstairs-landing-humidity"
      value_template: "{{ value_json.humidity | round(3) }}"
    - name: "Upstairs Bathroom Temperature"
      state_topic: "brompton/upstairs-bathroom/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      unique_id: "upstairs-bathroom-temperature"
      value_template: "{{ value_json.temperature | round(2) }}"
    - name: "Upstairs Bathroom Humidity"
      state_topic: "brompton/upstairs-bathroom/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      unique_id: "upstairs-bathroom-humidity"
      value_template: "{{ value_json.humidity | round(3) }}"
    - name: "Top of Hot Water Tank Temperature"
      state_topic: "brompton/hot-water-tank/top/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      unique_id: "hot-water-tank-top-temperature"
      value_template: "{{ value_json.temperature | round(2) }}"
    - name: "Bottom of Hot Water Tank Temperature"
      state_topic: "brompton/hot-water-tank/bottom/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      unique_id: "hot-water-tank-bottom-temperature"
      value_template: "{{ value_json.temperature | round(2) }}"
    - name: tesla_state
      state_topic: "teslamate/cars/1/state"
      unique_id: "teslamate-cars-1-state"
      icon: mdi:car-connected
    - name: tesla_geofence
      state_topic: "teslamate/cars/1/geofence"
      unique_id: "teslamate-cars-1-geofence"
      icon: mdi:earth
    - name: tesla_latitude
      state_topic: "teslamate/cars/1/latitude"
      unique_id: "teslamate-cars-1-latitude"
      unit_of_measurement: °
      icon: mdi:crosshairs-gps
    - name: tesla_longitude
      state_topic: "teslamate/cars/1/longitude"
      unique_id: "teslamate-cars-1-longitude"
      unit_of_measurement: °
      icon: mdi:crosshairs-gps
    - name: tesla_shift_state
      state_topic: "teslamate/cars/1/shift_state"
      unique_id: "teslamate-cars-1-shift-state"
      icon: mdi:car-shift-pattern
    - name: tesla_speed
      state_topic: "teslamate/cars/1/speed"
      unique_id: "teslamate-cars-1-speed"
      unit_of_measurement: "km/h"
      icon: mdi:speedometer
    - name: tesla_power
      state_topic: "teslamate/cars/1/power"
      unique_id: "teslamate-cars-1-power"
      device_class: power
      unit_of_measurement: W
      icon: mdi:flash
    - name: tesla_elevation
      state_topic: "teslamate/cars/1/elevation"
      unique_id: "teslamate-cars-1-elevation"
      unit_of_measurement: m
      icon: mdi:image-filter-hdr
    - name: tesla_inside_temp
      state_topic: "teslamate/cars/1/inside_temp"
      unique_id: "teslamate-cars-1-inside-temperature"
      device_class: temperature
      unit_of_measurement: °C
      icon: mdi:thermometer-lines
    - name: tesla_outside_temp
      state_topic: "teslamate/cars/1/outside_temp"
      unique_id: "teslamate-cars-1-outside-temperature"
      device_class: temperature
      unit_of_measurement: °C
      icon: mdi:thermometer-lines
    - name: tesla_odometer
      state_topic: "teslamate/cars/1/odometer"
      unique_id: "teslamate-cars-1-odometer"
      unit_of_measurement: km
      icon: mdi:counter
    - name: tesla_est_battery_range_km
      state_topic: "teslamate/cars/1/est_battery_range_km"
      unique_id: "teslamate-cars-1-estimated-range"
      unit_of_measurement: km
      icon: mdi:gauge
    - name: tesla_usable_battery_level
      state_topic: "teslamate/cars/1/usable_battery_level"
      unique_id: "teslamate-cars-1-usable-battery-level"
      device_class: battery
      unit_of_measurement: "%"
      icon: mdi:battery-80
    - name: tesla_charge_energy_added
      state_topic: "teslamate/cars/1/charge_energy_added"
      unique_id: "teslamate-cars-1-charge-energy-added"
      device_class: energy
      unit_of_measurement: kWh
      icon: mdi:battery-charging
    - name: tesla_charger_actual_current
      state_topic: "teslamate/cars/1/charger_actual_current"
      unique_id: "teslamate-cars-1-current"
      device_class: current
      unit_of_measurement: A
      icon: mdi:lightning-bolt
    - name: tesla_charger_power
      state_topic: "teslamate/cars/1/charger_power"
      unique_id: "teslamate-cars-1-charger-power"
      device_class: power
      unit_of_measurement: kW
      icon: mdi:lightning-bolt
    - name: tesla_time_to_full_charge
      state_topic: "teslamate/cars/1/time_to_full_charge"
      unique_id: "teslamate-cars-1-time-to-full-charge"
      unit_of_measurement: h
      device_class: duration
      icon: mdi:clock-outline

# Enables a map showing the location of tracked devices
map:

zone:
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 150
    icon: mdi:home
  - name: David Work
    latitude: !secret zone_david_work_latitude
    longitude: !secret zone_david_work_longitude
    radius: 150
    icon: mdi:briefcase

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Cloud
cloud:

sonos:

lovelace:
  mode: storage
  dashboards:
    brompton-dashboard:
      mode: yaml
      title: Brompton
      icon: mdi:script
      show_in_sidebar: true
      filename: brompton.yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
