# Front Big Bedroom
sensor.front_big_bedroom_temperature:
  friendly_name: Temperature
  icon: mdi:thermometer
sensor.front_big_bedroom_humidity:
  friendly_name: Humidity
  icon: mdi:water-percent
sensor.front_big_bedroom_pressure:
  friendly_name: Pressure
  icon: mdi:gauge

# Front Small Bedroom
sensor.front_small_bedroom_temperature:
  friendly_name: Temperature
  icon: mdi:thermometer
sensor.front_small_bedroom_humidity:
  friendly_name: Humidity
  icon: mdi:water-percent
sensor.front_small_bedroom_pressure:
  friendly_name: Pressure
  icon: mdi:gauge

# Back Big Bedroom
sensor.back_big_bedroom_temperature:
  friendly_name: Temperature
  icon: mdi:thermometer
sensor.back_big_bedroom_humidity:
  friendly_name: Humidity
  icon: mdi:water-percent
sensor.back_big_bedroom_pressure:
  friendly_name: Pressure
  icon: mdi:gauge

# Back Small Bedroom
sensor.back_small_bedroom_temperature:
  friendly_name: Temperature
  icon: mdi:thermometer
sensor.back_small_bedroom_humidity:
  friendly_name: Humidity
  icon: mdi:water-percent
sensor.back_small_bedroom_pressure:
  friendly_name: Pressure
  icon: mdi:gauge

# Kitchen
light.kitchen_lamp:
  friendly_name: Kitchen Lamp
  hidden: true

# Sitting Room
sensor.aqara_wsdcgq12lm_sitting_room_humidity:
  friendly_name: Humidity
  icon: mdi:water-percent
  unit_of_measurement: '%RH'
sensor.aqara_wsdcgq12lm_sitting_room_temperature:
  friendly_name: Temperature
  icon: mdi:thermometer
sensor.aqara_wsdcgq12lm_sitting_room_pressure:
  friendly_name: Pressure
  icon: mdi:gauge
sensor.aqara_wsdcgq12lm_sitting_room_battery:
  friendly_name: Battery
  icon: mdi:battery

# Upstairs Landing
sensor.upstairs_landing_temperature:
  friendly_name: Temperature
  icon: mdi:thermometer
sensor.upstairs_landing_humidity:
  friendly_name: Humidity
  icon: mdi:water-percent
sensor.upstairs_landing_pressure:
  friendly_name: Pressure
  icon: mdi:gauge

# Hallway
light.hallway_lamp:
  friendly_name: Hallway Lamp
  hidden: true

sensor.owm_cloud_coverage:
  friendly_name: Cloud Coverage
  icon: mdi:weather-cloudy
sensor.owm_condition:
  friendly_name: Current Weather Condition
sensor.owm_humidity:
  friendly_name: Humidity
  icon: mdi:water-percent
sensor.owm_pressure:
  friendly_name: Pressure
  icon: mdi:gauge
sensor.owm_temperature:
  friendly_name: Temperature
sensor.owm_wind_bearing:
  friendly_name: Wind Bearing
  icon: mdi:sign-direction
sensor.owm_wind_speed:
  friendly_name: Wind Speed
  icon: mdi:weather-windy
sensor.tradfri_remote_control:
  friendly_name: Light Remote Control

sun.sun:
  hidden: true

light.tradfri_group:
  hidden: true

device_tracker.mqtt_david_phone:
  friendly_name: David's Phone
