apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  orgId: 1
  url: http://192.168.1.12:8086
  user: influxdb-read
  database: brompton
  withCredentials: true
  isDefault: false
  version: 1
  editable: false
  secureJsonData:
    password: ${INFLUXDB_READ_USER_PASSWORD}
