homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

mqtt:
  broker: 192.168.1.12
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enables a map showing the location of tracked devices
map:

zone:
  - name: Home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 150
    icon: mdi:home
  - name: David Work
    latitude: !secret zone_david_work_latitude
    longitude: !secret zone_david_work_longitude
    radius: 150
    icon: mdi:briefcase

device_tracker:
  - platform: owntracks
    waypoints: true

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - wind_bearing
      - pressure
      - clouds
      - rain
      - snow
      - humidity

# Nest
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# IKEA Trådfri (Tradfri)
tradfri:
  host: 192.168.1.171

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Chromecast
media_player:
  - platform: cast
    host: 192.168.1.153

# Test Sensors
# Move into sensor.yaml eventually
sensor:
  - platform: mqtt
    state_topic: 'test/sensor1'
    name: 'Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
