Kitchen:
  entities:
    - sensor.kitchen_nest_protect_co_status
    - sensor.kitchen_nest_protect_smoke_status
    - light.kitchen_lamp
Living Room:
  entities:
    - sensor.living_room_nest_protect_co_status
    - sensor.living_room_nest_protect_smoke_status
Upstairs:
  entities:
    - sensor.upstairs_nest_protect_co_status
    - sensor.upstairs_nest_protect_smoke_status
Hallway:
  entities:
    - light.hallway_lamp
Outside:
  entities:
    - sensor.owm_cloud_coverage
    - sensor.owm_condition
    - sensor.owm_humidity
    - sensor.owm_pressure
    - sensor.owm_rain
    - sensor.owm_snow
    - sensor.owm_temperature
    - sensor.owm_wind_bearing
    - sensor.owm_wind_speed

Spaces:
  view: yes
  name: Spaces
  entities:
    - group.living_room
    - group.kitchen
    - group.upstairs
    - group.hallway
    - group.outside
