version: '3.1'
services:
  homeassistant:
    image: homeassistant/home-assistant:0.60
    volumes:
      - ./configuration:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
