version: '3.8'
services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - SERVERURL=vpn.dashford.io
      - SERVERPORT=52000
      - PEERS=phone
      - PEERDNS=auto
    volumes:
      - wgconfig:/config
      - /lib/modules:/lib/modules
    ports:
      - 52000:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  homeassistant:
    image: homeassistant/home-assistant:2023.5.4
    container_name: homeassistant
    network_mode: host
    volumes:
      - ./docker/homeassistant/configuration:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123
      - 8124:8124
    depends_on:
      - homeassistant_db
      - mosquitto
      - influxdb

  mosquitto:
    build:
      context: ./docker/mosquitto
      args:
        - USERNAME=${MQTT_USER}
        - PASSWORD=${MQTT_PASSWORD}
    container_name: mosquitto
    ports:
      - 1883:1883
    restart: unless-stopped
    volumes:
      - ./docker/mosquitto/configuration/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  influxdb:
    image: influxdb:2.7.1
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME={INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=dashford
      - DOCKER_INFLUXDB_INIT_BUCKET=brompton
      - INFLUXD_LOG_LEVEL=error
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

  homeassistant_db:
    image: postgres:15.3
    container_name: homeassistant_db
    environment:
      - POSTGRES_PASSWORD=${HOMEASSISTANT_DB_PASSWORD}
      - POSTGRES_DB=homeassistant
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
      - TZ=Europe/Dublin
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - homeassistant_db:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    volumes:
      - grafana:/data
      - ./docker/grafana/configuration:/etc/grafana
      - ./docker/grafana/dashboards/brompton:/var/lib/grafana/dashboards/brompton
      - ./docker/grafana/dashboards/teslamate:/var/lib/grafana/dashboards/teslamate
    network_mode: host
    ports:
      - 3000:3000
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_INSTALL_PLUGINS=pr0ps-trackmap-panel 2.1.2,natel-plotly-panel 0.0.7
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - TESLAMATE_DB_HOST=${TESLAMATE_HOST}
      - TESLAMATE_DB_PORT=5432
      - TESLAMATE_DB_USER=teslamate
      - TESLAMATE_DB_PASSWORD=${TESLAMATE_DB_PASSWORD}
      - TESLAMATE_DB_NAME=teslamate
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.30.4
    container_name: zigbee2mqtt
    volumes:
      - zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Dublin
      - ZIGBEE2MQTT_DATA=/app/data
      - ZIGBEE2MQTT_CONFIG_HOMEASSISTANT=true
      - ZIGBEE2MQTT_CONFIG_PERMIT_JOIN=false
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=${MQTT_USER}
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=${MQTT_PASSWORD}
      - ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC=zigbee2mqtt
      - ZIGBEE2MQTT_CONFIG_MQTT_CLIENT_ID=zigbee2mqtt
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER="mqtt://localhost"
      - ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL=debug
      - ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL=15
      - ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY=GENERATE
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT="/dev/ttyACM0"

  teslamate:
    image: teslamate/teslamate:1.27.2
    container_name: teslamate
    restart: unless-stopped
    environment:
      - ENCRYPTION_KEY=${TESLAMATE_ENCRYPTION_KEY}
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${TESLAMATE_DB_PASSWORD}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=10.243.0.100
      - DATABASE_PORT=5433
      - MQTT_HOST=mosquitto
      - MQTT_USERNAME=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - TZ=Europe/Dublin
    ports:
      - "4000:4000"
    depends_on:
      - teslamate_db

  teslamate_db:
    image: postgres:15.3
    container_name: teslamate_db
    environment:
      - POSTGRES_PASSWORD=${TESLAMATE_DB_PASSWORD}
      - POSTGRES_DB=teslamate
      - POSTGRES_USER=teslamate
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
      - TZ=Europe/Dublin
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - teslamate_db:/var/lib/postgresql/data

#  teslamateagile:
#    image: mattjeanes/teslamateagile:v1.11.2
#    container_name: teslamateagile
#    restart: unless-stopped
#    environment:
#      - DATABASE_USER=teslamate
#      - DATABASE_PASS=${TESLAMATE_DB_PASSWORD}
#      - DATABASE_NAME=teslamate
#      - DATABASE_HOST=10.243.0.100
#      - DATABASE_PORT=5433
#      - TeslaMate__UpdateIntervalSeconds=300
#      - TeslaMate__GeofenceId=1
#      - TeslaMate__EnergyProvider=FixedPrice
#      - FixedPrice__TimeZone=Europe/Dublin
#      - FixedPrice__Prices__0=00:00-12:00=0.4346
#      - FixedPrice__Prices__1=12:00-00:00=0.4346

volumes:
  influxdb-data:
    driver: local
  influxdb-config:
    driver: local
  grafana:
    driver: local
  homeassistant_db:
    driver: local
  zigbee2mqtt:
    driver: local
  wgconfig:
    driver: local
  teslamate_db:
    driver: local
