version: '3.8'
services:
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - SERVERURL=vpn.dashford.io
      - SERVERPORT=51820
      - PEERS=phone
      - PEERDNS=auto
    volumes:
      - wgconfig:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  homeassistant:
    image: homeassistant/home-assistant:2022.3
    container_name: homeassistant
    network_mode: host
    volumes:
      - ./docker/homeassistant/configuration:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123

  mosquitto:
    build:
      context: ./docker/mosquitto
      args:
        - USERNAME=${MQTT_USER}
        - PASSWORD=${MQTT_PASSWORD}
    container_name: mosquitto
    ports:
      - 1883:1883
    restart: unless-stopped
    volumes:
      - ./docker/mosquitto/configuration/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME={INFLUXDB_ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=dashford
      - DOCKER_INFLUXDB_INIT_BUCKET=brompton
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2

  homeassistant_db:
    image: postgres:14.1
    container_name: homeassistant_db
    environment:
      - POSTGRES_PASSWORD=${HOMEASSISTANT_DB_PASSWORD}
      - POSTGRES_DB=homeassistant
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
      - TZ=Europe/Dublin
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - homeassistant_db:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:8.4.3
    container_name: grafana
    volumes:
      - grafana:/data
      - ./docker/grafana/configuration:/etc/grafana
      - ./docker/grafana/dashboards/brompton:/var/lib/grafana/dashboards/brompton
      - ./docker/grafana/dashboards/teslamate:/var/lib/grafana/dashboards/teslamate
    network_mode: host
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_DOMAIN=grafana.dashford.io
      - GF_SERVER_ROOT_URL=https://grafana.dashford.io
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - TESLAMATE_DB_HOST=teslamate_db
      - TESLAMATE_DB_PORT=5433
      - TESLAMATE_DB_USER=teslamate
      - TESLAMATE_DB_PASSWORD=${TESLAMATE_DB_PASSWORD}
      - TESLAMATE_DB_NAME=teslamate
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.24.0
    container_name: zigbee2mqtt
    volumes:
      - zigbee2mqtt:/app/data
      - ./docker/zigbee2mqtt/configuration.yaml:/app/data/configuration.yaml:rw
      - ./docker/zigbee2mqtt/secret.yaml:/app/data/secret.yaml:ro
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Dublin
      - ZIGBEE2MQTT_DATA=/app/data
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=${MQTT_USER}
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=${MQTT_PASSWORD}

  teslamate:
    image: teslamate/teslamate:1.26.1
    restart: unless-stopped
    environment:
      - ENCRYPTION_KEY=${TESLAMATE_ENCRYPTION_KEY}
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${TESLAMATE_DB_PASSWORD}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=teslamate_db
      - DATABASE_PORT=5433
      - MQTT_HOST=mosquitto
      - MQTT_USERNAME=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - TZ=Europe/Dublin
    ports:
      - 4000:4000
    depends_on:
      - teslamate_db

  teslamate_db:
    image: postgres:14.1
    container_name: teslamate_db
    environment:
      - POSTGRES_PASSWORD=${TESLAMATE_DB_PASSWORD}
      - POSTGRES_DB=teslamate
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
      - TZ=Europe/Dublin
    ports:
      - "5433:5432"
    restart: unless-stopped
    volumes:
      - teslamate_db:/var/lib/postgresql/data

volumes:
  influxdb-data:
    driver: local
  influxdb-config:
    driver: local
  grafana:
    driver: local
  homeassistant_db:
    driver: local
  zigbee2mqtt:
    driver: local
  wgconfig:
    driver: local
  teslamate_db:
    driver: local
