version: '3.1'
services:
  acme.sh:
    image: dashford/arm32v7-acme.sh:2.8.2
    container_name: acme.sh
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acmesh-certs:/etc/acme.sh/ssl
    environment:
      - CF_Account_ID=${CF_Account_ID}
      - CF_Token=${CF_Token}

  nginx-proxy:
    image: nginx:1.17.6
    container_name: nginx-proxy
    environment:
      - X_HA_ACCESS=${X_HA_ACCESS}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - acmesh-certs:/etc/acme.sh/ssl:ro
      - ./docker/nginx/ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem:ro
      - ./docker/nginx/html:/var/www/html

  homeassistant:
    image: homeassistant/raspberrypi2-homeassistant:0.102.1
    container_name: homeassistant
    volumes:
      - ./docker/homeassistant/configuration:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    ports:
      - 8123:8123

  mosquitto:
    image: eclipse-mosquitto:1.6.8
    container_name: mosquitto
    volumes:
      - ./docker/mosquitto/configuration:/mosquitto/config
      - acmesh-certs:/etc/acme.sh/ssl:ro
    ports:
      - 1883:1883
      - 8883:8883

  influxdb:
    image: influxdb:1.7.9
    container_name: influxdb
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=false
      - INFLUXDB_DB=brompton
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_READ_USER=influxdb-read
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
      - INFLUXDB_WRITE_USER=influxdb-write
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
    ports:
      - 8086:8086
      - 8083:8083

  grafana:
    image: grafana/grafana:6.5.1
    container_name: grafana
    volumes:
      - grafana:/data
      - ./docker/grafana/configuration:/etc/grafana
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_DOMAIN=grafana.dashford.io
      - GF_SERVER_ROOT_URL=https://grafana.dashford.io
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_DISABLE_LOGIN_FORM=false

  telegraf:
    image: telegraf:1.12.6
    container_name: telegraf
    volumes:
      - ./docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - MQTT_USERNAME=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}

volumes:
  influxdb:
    driver: local
  grafana:
    driver: local
  acmesh-certs:
    driver: local
