version: '3.1'
services:
  homeassistant:
    image: lroguet/rpi-home-assistant:0.60.0
    volumes:
      - ./configuration:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
