version: '3.1'
services:
  homeassistant:
    build: docker/homeassistant
    volumes:
      - ./configuration:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    ports:
      - 8123:8123
