version: '3.1'
services:
  nginx:
    image: tobi312/rpi-nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/arm32v7/nginx/config:/etc/nginx/conf.d:ro
      - ./docker/arm32v7/nginx/ssl:/etc/nginx/ssl:ro
      - ./docker/arm32v7/nginx/html:/var/www/html
      - certificates:/etc/letsencrypt

  letsencrypt:
    build: docker/arm32v7/letsencrypt
    environment:
      - LETSENCRYPT_USER_MAIL=${LETSENCRYPT_USER_MAIL}
      - LEXICON_PROVIDER=cloudflare
      - LEXICON_CLOUDFLARE_USERNAME=${LEXICON_CLOUDFLARE_USERNAME}
      - LEXICON_CLOUDFLARE_TOKEN=${LEXICON_CLOUDFLARE_TOKEN}
      - LETSENCRYPT_STAGING=false
      - CERTS_DIRS_MODE=0755
      - CERTS_FILES_MODE=0644
    volumes:
      - ./docker/arm32v7/letsencrypt/domains.conf:/etc/letsencrypt/domains.conf
      - certificates:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  homeassistant:
    build: docker/arm32v7/homeassistant
    volumes:
      - ha:/ha-installation
      - ./docker/arm32v7/homeassistant/configuration:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: host
    ports:
      - 8123:8123

  mosquitto:
    build: docker/arm32v7/mosquitto
    volumes:
      - ./docker/arm32v7/mosquitto/configuration:/config
      - certificates:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 1883:1883
      - 8883:8883

  influxdb:
    image: arm32v7/influxdb:1.5.1
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=false
      - INFLUXDB_DB=homeassistant
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_READ_USER=influxdb-read
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
      - INFLUXDB_WRITE_USER=influxdb-write
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
    ports:
      - 8086:8086
      - 8083:8083

  grafana:
    image: zeiot/rpi-grafana:v5.0.0
    volumes:
      - grafana:/data
      - ./docker/arm32v7/grafana:/etc/grafana
      - certificates:/etc/letsencrypt
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=change-me-later
#      - GF_AUTH_DISABLE_LOGIN_FORM=true
#      - GF_AUTH_GITHUB_ENABLED=true

volumes:
  certificates:
    driver: local
  ha:
    driver: local
  influxdb:
    driver: local
  grafana:
    driver: local
