version: '3.1'
services:
  certbot:
    build: docker/certbot

  homeassistant:
    build: docker/homeassistant
    volumes:
      - ./configuration:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    ports:
      - 8123:8123

  mosquitto:
    build: docker/mosquitto
    volumes:
      - ./docker/mosquitto/configuration:/config
    ports:
      - 1883:1883
