version: '3.1'
services:
  nginx-proxy:
    image: arm32v7/nginx:1.15.5
    labels:
      - sh.acme.autoload.domain=*.dashford.io
    environment:
      - X_HA_ACCESS=${X_HA_ACCESS}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/arm32v7/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/arm32v7/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/arm32v7/nginx/ssl:/etc/nginx/ssl:ro
      - ./docker/arm32v7/nginx/html:/var/www/html

  nginx-proxy-acmesh:
    image: dashford/arm32v7-acme.sh:2.8.2
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acmeout:/acme.sh
    environment:
      - CF_Account_ID=${CF_Account_ID}
      - CF_Token=${CF_Token}
      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=*.dashford.io
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/acme.sh/ssl/*.dashford.io/key.pem
      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/acme.sh/ssl/*.dashford.io/cert.pem"
      - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/acme.sh/ssl/*.dashford.io/ca.pem"
      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/acme.sh/ssl/*.dashford.io/full.pem"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload"

  homeassistant:
    image: homeassistant/raspberrypi2-homeassistant:0.81.0
    volumes:
      - ./docker/arm32v7/homeassistant/configuration:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
    ports:
      - 8123:8123

  mosquitto:
    image: dashford/arm32v7-mosquitto:1.5.3
    labels:
      - sh.acme.autoload.domain=mqtt.dashford.io
    volumes:
      - ./docker/arm32v7/mosquitto/configuration:/config
    ports:
      - 1883:1883
      - 8883:8883

  mosquitto-acmesh:
    image: dashford/arm32v7-acme.sh:2.8.2
    command: daemon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acmeout:/acme.sh
    environment:
      - CF_Account_ID=${CF_Account_ID}
      - CF_Token=${CF_Token}
      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=mqtt.dashford.io
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/acme.sh/ssl/mqtt.dashford.io/key.pem
      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/acme.sh/ssl/mqtt.dashford.io/cert.pem"
      - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/acme.sh/ssl/mqtt.dashford.io/ca.pem"
      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/acme.sh/ssl/mqtt.dashford.io/full.pem"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service mosquitto restart"

  influxdb:
    image: arm32v7/influxdb:1.6.4
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=false
      - INFLUXDB_DB=brompton
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_READ_USER=influxdb-read
      - INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_READ_USER_PASSWORD}
      - INFLUXDB_WRITE_USER=influxdb-write
      - INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_WRITE_USER_PASSWORD}
    ports:
      - 8086:8086
      - 8083:8083

  grafana:
    # https://hub.docker.com/r/proxx/grafana-armv7/
    image: zeiot/rpi-grafana:v5.0.0
    volumes:
      - grafana:/data
      - ./docker/arm32v7/grafana:/etc/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_DOMAIN=grafana.dashford.io
      - GF_SERVER_ROOT_URL=https://grafana.dashford.io
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_AUTH_DISABLE_LOGIN_FORM=false

  telegraf:
    image: arm32v7/telegraf:1.8.3
    volumes:
      - ./docker/arm32v7/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - MQTT_USERNAME=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}

volumes:
  influxdb:
    driver: local
  grafana:
    driver: local
