sensor.kitchen_nest_protect_co_status:
  friendly_name: Carbon Monoxide Status
sensor.living_room_nest_protect_co_status:
  friendly_name: Carbon Monoxide Status
sensor.upstairs_nest_protect_co_status:
  friendly_name: Carbon Monoxide Status
sensor.kitchen_nest_protect_battery_health:
  friendly_name: Nest Battery
sensor.living_room_nest_protect_battery_health:
  friendly_name: Nest Battery
sensor.upstairs_nest_protect_battery_health:
  friendly_name: Nest Battery
sensor.kitchen_nest_protect_smoke_status:
  friendly_name: Smoke Status
sensor.living_room_nest_protect_smoke_status:
  friendly_name: Smoke Status
sensor.upstairs_nest_protect_smoke_status:
  friendly_name: Smoke Status

binary_sensor.kitchen_nest_protect_online:
  friendly_name: Nest Online
binary_sensor.living_room_nest_protect_online:
  friendly_name: Nest Online
binary_sensor.upstairs_nest_protect_online:
  friendly_name: Nest Online

light.kitchen_lamp:
  friendly_name: Kitchen Lamp
light.hallway_lamp:
#  icon: mdi:lightbulb
  friendly_name: Hallway Lamp

sun.sun:
  hidden: true
