apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  orgId: 1
  url: ${INFLUXDB_HOST}
  user: influxdb-read
  database: brompton
  withCredentials: true
  isDefault: false
  version: 1
  editable: false
  secureJsonData:
    password: ${INFLUXDB_READ_USER_PASSWORD}
- name: Sun and Moon
  type: fetzerch-sunandmoon-datasource
  orgId: 1
  editable: false
