apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://192.168.1.10:8086
  user: admin
  isDefault: true
  version: 1
  editable: false
  jsonData:
    version: Flux
    organization: dashford
    defaultBucket: brompton
    tlsSkipVerify: true
  secureJsonData:
    token: ${INFLUXDB_ADMIN_TOKEN}
