apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://192.168.1.10:8086
  user: admin
  isDefault: true
  version: 1
  editable: false
  withCredentials: true
  basicAuth: true
  basicAuthUser: admin
  jsonData:
    version: Flux
    organization: dashford
    defaultBucket: brompton
    tlsSkipVerify: true
  secureJsonData:
    basicAuthPassword: ${INFLUXDB_ADMIN_PASSWORD}
    token: ${INFLUXDB_ADMIN_TOKEN}
- name: TeslaMate
  type: postgres
  url: http://192.168.1.10:5433
  user: ${TESLAMATE_DB_USER}
  database: ${TESLAMATE_DB_NAME}
  password: ""
  access: proxy
  basicAuth: false
  withCredentials: true
  isDefault: false
  secureJsonData:
    password: ${TESLAMATE_DB_PASSWORD}
  jsonData:
    postgresVersion: 1200
    sslmode: disable
  version: 1
  editable: false
