apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  orgId: 1
  url: ${INFLUXDB_HOST}
  user: admin
  database: brompton
  withCredentials: true
  isDefault: true
  version: 1
  editable: false
  secureJsonData:
    password: ${INFLUXDB_ADMIN_PASSWORD}
