apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  orgId: 1
  url: ${INFLUXDB_HOST}
  user: influxdb-read
  database: brompton
  withCredentials: true
  isDefault: false
  version: 1
  editable: false
  secureJsonData:
    password: ${INFLUXDB_READ_USER_PASSWORD}
- name: InfluxDB-HA
  type: influxdb
  orgId: 1
  url: ${INFLUXDBHA_HOST}
  user: influxdb-read
  database: home_assistant
  withCredentials: true
  isDefault: false
  version: 1
  editable: false
  secureJsonData:
    password: ${INFLUXDBHA_READ_USER_PASSWORD}
